type Mutation{
    signIn(input: signInInput): token
    signUp(input: signUpInput): user
    editUser(input: userEditInput): user
    deleteUser(id: ID!): user
    lessonViewed(input: lessonViewedInput): userLesson
}
type Query{
    course(id: ID!): course
    courses: [course]
    chapter(id: ID!): chapter
    chapters(course_id: ID!): [chapter]
    lesson(id: ID!): lesson
    lessons(chapter_id: ID!): [lesson]
    user: user
    #remove
    allChapters: [chapter]
    allLessons: [lesson]
    users: [user]
}
input signInInput{
    email: String!
    password: String!
}
input signUpInput {
    name: String!
    email: String!
    password:String!
}
input userEditInput {
    name: String
    password: String
    email: String
}
input lessonViewedInput{
    user_id: String!
    lesson_id: String!
    viewed: Boolean!
}
type course{
    id: ID!
    name: String!
    creation: String!
    chapters: [chapter]
}
type chapter{
    id: ID!
    name: String!
    course_id: ID!
    lessons: [lesson]
}
type lesson{
    id: ID!
    name: ID!
    link: String!
    chapter_id: ID!
}

type user{
    id: ID!
    name: String!
    email: String!
    date: String!
    creation: String!
    #eliminar el password
    password: String!
    lessons: [userLesson]
    courses: [userCourse]
}
type token{
    auth: Boolean!
    body: String
}
type userLesson{
    id: ID!
    user_id: ID!
    lesson_id: ID!
    viewed: Boolean!
    date: String!
}
type userCourse{
    id: ID!
    name: String!
    value: Int
    total: Int
}