type Mutation{
    signUp(input: signUpInput): user
    editUser(input: userEditInput): user
    deleteUser(id: ID!): user
}
type Query{
    course(_id: ID!): course
    courses: [course]
    chapter(_id: ID!): chapter
    allChapters: [chapter]
    chapters(course_id: ID!): [chapter]
    allLessons: [lesson]
    lesson(_id: ID!): lesson
    lessons(chapter_id: ID!): [lesson]
    users: [user]
    signIn(input: signInInput): token
}
input signInInput{
    email: String!
    password: String!
}
input signUpInput {
    name: String!
    email: String!
    password:String!
}
input userEditInput {
    name: String
    password: String
    email: String
}
type course{
    _id: ID!
    name: String!
    chapters(course_id: ID!): [chapter]
}
type chapter{
    _id: ID!
    name: String!
    course_id: ID!
    lessons: [lesson]
}
type lesson{
    _id: ID!
    name: ID!
    link: String!
    chapter_id: ID!
}

type user{
    _id: ID!
    name: String!
    email: String!
    password:String!
}
type token{
    body: String!
}