SET @CHAPTER_1 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_2 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_3 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_4 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_5 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_6 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_7 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_8 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_9 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_10 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));
SET @CHAPTER_11 = (LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16))))));


SET @COURSE_ID = 1;
SET @COURSE_NAME = 'OTHER';

INSERT INTO `courses` (`id`, `name`) VALUES
(@COURSE_ID, @COURSE_NAME),
INSERT INTO `chapters` (`id`, `name`, `course_id`) VALUES
(@CHAPTER_1, '',COURSE_ID),
(@CHAPTER_2, '', @COURSE_ID),
(@CHAPTER_3, '', @COURSE_ID),
(@CHAPTER_4, '',COURSE_ID),
(@CHAPTER_5, '', @COURSE_ID),
(@CHAPTER_6, '', @COURSE_ID),
(@CHAPTER_7, '', @COURSE_ID),
(@CHAPTER_8, '', @COURSE_ID),
(@CHAPTER_9, '', @COURSE_ID),
(@CHAPTER_10, '' @COURSE_ID),
(@CHAPTER_11, '',@COURSE_ID),
(@CHAPTER_12, '', @COURSE_ID),
(@CHAPTER_13, '', @COURSE_ID),
(@CHAPTER_14, '', @COURSE_ID),
(@CHAPTER_15, '', @COURSE_ID),
(@CHAPTER_16, '', @COURSE_ID);




INSERT INTO `lessons` (`id`, `name`, `link`, `COURSE_ID`) VALUES
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_1),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_1),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_1),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_1),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_1),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_2),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_2),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_2),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_2),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_3),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_3),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_3),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_3),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_3),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_3),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_4),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_4),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_4),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_5),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_5),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_5),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_5),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_5),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_6),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_6),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_7),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_7),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_7),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_7),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_7),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_8),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_8),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_8),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_8),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_8),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_8),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_9),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_9),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_9),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_10),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_10),
((LOWER(CONCAT(HEX(UNIX_TIMESTAMP()),HEX(UUID_SHORT()),HEX(FLOOR(RAND()*(16)))))), '', '', @CHAPTER_11);
